# site settings
title: Angela Tian
subtitle: UBC CS, 4th year
email: tiangela1@gmail.com
description: I'm currently a fourth-year UBC CS student, on co-op.<br />I'm interested in devops, game dev, and back-end web dev.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Angela Tian
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
# 500px_url:
# facebook_url: 
github_url: https://github.com/tiangela1027
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/tiangela/
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
