# site settings
title: Angela Tian
subtitle: UBC CS, 4th year
email: tiangela1@gmail.com
description: I'm a fourth-year Computer Science (BSc) student at UBC,<br />striving to make headlines out of my better thoughts.<br /><br />My interests are DevOps and Cloud.<br />I also like to write.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Angela Tian

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/tiangela1027
linkedin_url: https://www.linkedin.com/in/tiangela/

# build settings
markdown: kramdown

sass:
  style: compressed
